url: https://hanfang.github.io
# baseurl: /agency-jekyll-theme/

# Site settings
title: Han Fang
email: hanfang.cshl@gmail.com
description: "Han Fang - Github Page"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Han Fang
  pic: img/about/hanfang.png
  position: PhD student @ Cold Spring Harbor Laboratory and Stony Brook University
  social:
  - title: twitter
    url: https://twitter.com/Han_Fang_
  - title: linkedin
    url:  https://www.linkedin.com/in/hfang15
  - title: github
    url: http://hanfang.github.io/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/Han_Fang_
  - title: linkedin
    url:  https://www.linkedin.com/in/hfang15
  - title: github
    url: http://hanfang.github.io/

# Postal address (add as many lines as necessary)
address:
  - line: 1 Bungtown Rd,
  - line: Cold Spring Harbor, NY 11724

# Build settings
markdown: kramdown
permalink: pretty
