url: https://shaniavina.github.io
# baseurl: /agency-jekyll-theme/

# Site settings
title: Shanshan Li
email: shaniavina@gmail.com
description: "Shanshan Li - Github Page"

# Color settings (hex-codes without the leading hash-tag)
color:
  primary: fed136
  secondary: fec503
  secondary-dark: 333

# Team names, titles and social links
people:
- name: Shanshan Li
  pic: img/about/shanshanli.jpg
  position: Ph.D @ Stony Brook University and Cold Spring Harbor Laboratory
  social:
  - title: twitter
    url: https://twitter.com/shaniavina
  - title: linkedin
    url:  https://www.linkedin.com/in/shanshan-li-97607742/
  - title: github
    url: http://shaniavina.github.io/

# Social networks usernames (many more available: google-plus, flickr, dribbble, pinterest, instagram, tumblr, linkedin, etc.)
social:
  - title: twitter
    url: https://twitter.com/shaniavina
  - title: linkedin
    url:  https://www.linkedin.com/in/shanshan-li-97607742/
  - title: github
    url: http://shaniavina.github.io/

# Postal address (add as many lines as necessary)
address:
  - line: John S. Toll Drive,
  - line: Stony Brook, NY 11794

# Build settings
markdown: kramdown
permalink: pretty
